cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('checkout/', views.cart_checkout, name="checkout"),
    path('clear/', views.cart_clear, name="clear"),
    path('thank/', views.thank_you, name="thanks"),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import index, bookdetail, bookCategory, allbook
app_name = "shop"
urlpatterns = [
    path('', index, name='index'),
    path('book/<int:id>/<slug:slug>/', bookdetail, name='bookdetail'),
    path('category/<int:id>',bookCategory, name="category"),
    path('allboook/', allbook, name="allbook"),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    override = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Book
from .cart import Cart
from .forms import CartAddProductForm
from django.contrib.auth.decorators import login_required



@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Book, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
        quantity=cd['quantity'],
        override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Book, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})


@login_required(login_url="account:login")
def cart_checkout(request):
    cart = Cart(request)
    return render(request, 'cart/checkout.html', {'cart': cart})

def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:thanks')

def thank_you(request):
    return render(request, 'cart/thanks.html')

templates/cart/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Checkout</title>
{% endblock title %}

{% block content %}
<div class="container">
  <div class="row g-5">
      <div class="col-md-5 col-lg-4 order-md-last">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-primary">Your cart</span>
        </h4>
        <ul class="list-group mb-3">
          {% for item in cart %}
              {% with product=item.product %}
                <li class="list-group-item d-flex justify-content-between lh-sm">        
                  <div>
                    <h6 class="my-0">{{ product.name }}</h6>
                    <small class="text-muted">{{ item.quantity }}</small>
                  </div>
                  <span class="text-muted">Rs{{ item.price }}</span>
                </li>
              {% endwith %}
          {% endfor %}
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (Rs)</span>
            <strong>Rs{{ cart.get_total_price }}</strong>
          </li>
        </ul>
      </div>
      <div class="col-md-7 col-lg-8">
        <h4 class="mb-3">Billing address</h4>
        <form class="needs-validation" novalidate="">
          <div class="row g-3">
            <div class="col-sm-6">
              <label for="firstName" class="form-label">First name</label>
              <input type="text" class="form-control" id="firstName" placeholder="" value="" required="">
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

            <div class="col-sm-6">
              <label for="lastName" class="form-label">Last name</label>
              <input type="text" class="form-control" id="lastName" placeholder="" value="" required="">
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>

            <div class="col-12">
              <label for="username" class="form-label">Username</label>
              <div class="input-group has-validation">
                <span class="input-group-text">@</span>
                <input type="text" class="form-control" id="username" placeholder="Username" required="">
              <div class="invalid-feedback">
                  Your username is required.
                </div>
              </div>
            </div>

            <div class="col-12">
              <label for="email" class="form-label">Email <span class="text-muted">(Optional)</span></label>
              <input type="email" class="form-control" id="email" placeholder="you@example.com">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="col-12">
              <label for="address" class="form-label">Address</label>
              <input type="text" class="form-control" id="address" placeholder="1234 Main St" required="">
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>

            <div class="col-12">
              <label for="address2" class="form-label">Address 2 <span class="text-muted">(Optional)</span></label>
              <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
            </div>

            <div class="col-md-5">
              <label for="country" class="form-label">Country</label>
              <select class="form-select" id="country" required="">
                <option value="">Choose...</option>
                <option>Nepal</option>
              </select>
              <div class="invalid-feedback">
                Please select a valid country.
              </div>
            </div>

            <div class="col-md-4">
              <label for="state" class="form-label">City</label>
              <select class="form-select" id="state" required="">
                <option value="">Choose...</option>
                <option>Kathmandu</option>
                <option>Itahari</option>
                <option>Pokhara</option>
                <option>Lamjug</option>
              </select>
              <div class="invalid-feedback">
                Please provide a valid city.
              </div>
            </div>

            <div class="col-md-3">
              <label for="zip" class="form-label">Zip</label>
              <input type="text" class="form-control" id="zip" placeholder="" required="">
              <div class="invalid-feedback">
                Zip code required.
              </div>
            </div>
          </div>

          <hr class="my-4">


          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="save-info">
            <label class="form-check-label" for="save-info">Save this information for next time</label>
          </div>

          <hr class="my-4">

          <h4 class="mb-3">Payment</h4>

          <div class="my-3">
            <div class="form-check">
              <input id="credit" name="paymentMethod" type="radio" class="form-check-input" checked="" required="">
              <label class="form-check-label" for="credit">Credit card</label>
            </div>
            <div class="form-check">
              <input id="debit" name="paymentMethod" type="radio" class="form-check-input" required="">
              <label class="form-check-label" for="debit">Debit card</label>
            </div>
            <div class="form-check">
              <input id="paypal" name="paymentMethod" type="radio" class="form-check-input" required="">
              <label class="form-check-label" for="paypal">Cash on Delivery</label>
            </div>
          </div>

          <hr class="my-4">

          <a href="{% url 'cart:clear' %}" class="w-100 btn btn-primary btn-lg">Continue to checkout</a> 
        </form>
      </div>
  </div>
</div>
{% endblock content %}

templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Cart detail</title>
{% endblock title %}

{% block content %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">Image</th>
        <th scope="col">Book</th>
        <th scope="col">Quantity</th>
        <th scope="col">Remove</th>
        <th scope="col">Unit price</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td><img src="{{ product.image.url }}" class="img-fluid"></td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>
                        <form action="{% url "cart:cart_remove" product.id %}" method="post">
                            <input type="submit" class="btn btn-primary" value="Remove">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td>Rs{{ item.price }}</td>
                    <td>Rs{{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">Rs{{ cart.get_total_price }}</td>
        </tr>
    </tbody>
  </table>
  <a class="btn btn-primary" href="{% url 'cart:checkout' %}">Checkout</a>
{% endblock content %}

templates/cart/thanks.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Thanks</title>
{% endblock title %}

{% block content %}
<h3>Thank you your order has been placed </h3>
<a href="{% url 'shop:index' %}"> continue shopping</a>
{% endblock content %}