cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('checkout/', views.cart_checkout, name="checkout"),
    path('clear/', views.cart_clear, name="clear"),
    path('thank/', views.thank_you, name="thanks"),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import index, bookdetail, bookCategory, allbook
app_name = "shop"
urlpatterns = [
    path('', index, name='index'),
    path('book/<int:id>/<slug:slug>/', bookdetail, name='bookdetail'),
    path('category/<int:id>',bookCategory, name="category"),
    path('allboook/', allbook, name="allbook"),
]

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:category", kwargs={"id": self.id})

class Author(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)

    def __str__(self):
        return self.name

class Publication(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)

    def __str__(self):
        return self.name

class Book(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    category = models.ManyToManyField(Category)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/product/%Y/%m/%d")  
    desc = models.TextField()
    isbn = models.CharField(max_length=10, unique=True)
    price = models.IntegerField(null=True)
    edition = models.IntegerField()
    publication = models.ForeignKey(Publication, on_delete=models.CASCADE)
    published_date = models.DateTimeField(auto_now=True)
    update_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:bookdetail", kwargs={"id": self.id, "slug":self.slug})
    

shop/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from .models import Book, Category
from cart.forms import CartAddProductForm

# Create your views here.
def index(request):
    books = Book.objects.all()[:6]
    category = Category.objects.all()
    cart_product_form = CartAddProductForm()
    context={
        'books':books,
        'category':category,
        'cart_product_form': cart_product_form,
    }
    return render(request, 'shop/index.html', context)

def bookdetail(request, id, slug):
    book = get_object_or_404(Book, id=id, slug=slug)
    cart_product_form = CartAddProductForm()
    context={
        'book':book,
        'cart_product_form': cart_product_form,
    }
    return render(request, 'shop/bookdetail.html', context)

def bookCategory(request, id):
    books = get_list_or_404(Book, category=id)
    categories = Category.objects.all()
    cart_product_form = CartAddProductForm()
    context={
        'books':books,
        'categories':categories,
        'cart_product_form': cart_product_form,
    }
    return render(request, 'shop/category.html', context)

def allbook(request):
    books = get_list_or_404(Book)
    categories = Category.objects.all()
    cart_product_form = CartAddProductForm()
    context={
        'books':books,
        'categories':categories,
        'cart_product_form': cart_product_form,
    }
    return render(request, 'shop/category.html', context)

templates/shop/bookdetail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>{{book.name}}</title>
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row mt-2 mb-5">
        <div class="col-lg-4 col-4">
            <img src="{{book.image.url}}" class="img-fluid" alt="">
        </div>
        <div class="col-8">
            <h3>{{book.name}}</h3>
            <p>RS.{{book.price}}</p>
            <p>Author: {{book.author}}</p>
            <p>Publisher: {{book.publication}}</p>
            <p>Edition: {{book.edition}}</p>
            <p>Published date: {{book.published_date}}</p>
            <p>Updated date: {{book.update_date}}</p>
            <form action="{% url "cart:cart_add" book.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <input class="btn btn-primary" type="submit" value="Add to cart">
            </form>
        </div>
    
    </div>
    <div class="row">
        <div class="header text-center px-3">
            <h4 class="border-bottom border-success border-3">Short description</h4>
        </div>
        <p>{{book.desc}}</p>
    </div>
</div>
{% endblock content %}

templates/shop/category.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Category</title>
{% endblock title %}

{% block content %}
<div class="row m-auto hero">
    <div class="col-lg-3 col-3">
        <ul class="list-group">
            <li class="list-group-item"><h4>Category</h3></li>
            {% for cat in categories %}
            <li class="list-group-item"><a href="{{cat.get_absolute_url}}" class="nav-link">{{cat.name}}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-9 col-lg-9">
        <div class="row px-2">
            {% for book in books %}
                <div class="col-lg-4 col-md-12 mb-4">
                    <div class="card" style="width: 20rem;">
                        <a href="{{book.get_absolute_url}}"><img src="{{book.image.url}}" class="card-img-top" alt="..."></a>
                        <div class="card-body">
                          <h5 class="card-title">{{book.name}}</h5>
                          <p class="card-text">RS.{{book.price}}</p>
                          <form action="{% url "cart:cart_add" book.id %}" method="post">
                            {{ cart_product_form }}
                            {% csrf_token %}
                            <input class="btn btn-primary" type="submit" value="Add to cart">
                            </form>
                        </div>
                      </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

templates/shop/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Home</title>
{% endblock title %}

{% block content %}
  <!-- nav -->
  <div class="row m-auto hero mt-1">
    <div class="col-lg-4 col-12">
        <ul class="list-group">
            <li class="list-group-item"><h4>Category</h3></li>
            {% for cat in category %}
            <li class="list-group-item"><a href="{{cat.get_absolute_url}}" class="nav-link">{{cat.name}}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-12 col-lg-8">
        <div class="banner">
            <img src="{% static 'assets/image/banner/banner.jpg' %}" class="img-fluid" alt="...">
        </div>
    </div>
</div>
<!-- nav -->


<!-- feature product -->
<div class="feature-product py-2 mt-3">
    
        <div>
            <h2 class="text-center border-bottom border-success border-3 py-1">
            Latest Product
            </h2>
        </div>
        <div class="row px-2">
            {% for book in books %}
                <div class="col-lg-3 col-md-6 mb-4">
                    <div class="card" style="width: 20rem;">
                        <a href="{{book.get_absolute_url}}"><img src="{{book.image.url}}" class="card-img-top" alt="..."></a>
                        <div class="card-body">
                          <h5 class="card-title">{{book.name}}</h5>
                          <p class="card-text">RS.{{book.price}}</p>
                          <form action="{% url "cart:cart_add" book.id %}" method="post">
                            {{ cart_product_form }}
                            {% csrf_token %}
                            <input class="btn btn-primary" type="submit" value="Add to cart">
                           </form>
                        </div>
                      </div>
                </div>
            {% endfor %}
        </div>
    
</div>
<!-- feature product -->


{% endblock content %}