account/urls.py
from django.urls import path
from .views import userLogin, usersignup, profileCreate, profile, profileedit, userLogout

app_name="account"

urlpatterns = [
    path("login/", userLogin, name="login"),
    path('signup/', usersignup, name="signup"),
    path('logout/', userLogout, name="logout"),
    path('profilecreate/', profileCreate, name="profilecreate"),
    path('profileedit/', profileedit, name="profileedit"),
    path('profile/', profile, name="profile"),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('checkout/', views.cart_checkout, name="checkout"),
    path('clear/', views.cart_clear, name="clear"),
    path('thank/', views.thank_you, name="thanks"),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import index, bookdetail, bookCategory, allbook
app_name = "shop"
urlpatterns = [
    path('', index, name='index'),
    path('book/<int:id>/<slug:slug>/', bookdetail, name='bookdetail'),
    path('category/<int:id>',bookCategory, name="category"),
    path('allboook/', allbook, name="allbook"),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}
    {% endblock title %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'shop/css/style.css' %}">
  </head>
  <body>
    <!-- header -->
    <header>
        <div class="container">
            <!-- navbar -->
            <nav class="navbar navbar-expand-lg">
                <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'shop:index' %}">Shaja Book</a> 
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'shop:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:allbook' %}">All Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'cart:cart_detail' %}">
                                Cart <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            </a>
                        </li>
                        {% if request.user.is_authenticated %}
                            
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fa-solid fa-user"></i>
                                Profile
                                </a>
                                <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'account:profile' %}">Profile</a></li>
                                <li><a class="dropdown-item" href="{% url 'account:profileedit' %}">Edit Profile</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
                                </ul>
                            </li>
                            
                            
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account:login' %}">Login</a> 
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account:signup' %}">Singup</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
                </div>
            </nav>
            <!-- navbar -->
        </div>
    </header>
    <!-- header -->

    {% block content %}

    {% endblock content %}
    <!-- Footer -->
    <footer class="page-footer">

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">© 2022 Copyright:
            <a href="/">Aadarsha Rubin Amrit Ayush</a>
        </div>
        <!-- Copyright -->
    </footer>
  <!-- Footer -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>